### ISSUE TITLE
Impossible to add scoped npm packages

### ISSUE THREAD

**Issue by troglotit** [brillout/devarchy#6]
I wanted to add [blueprint](https://github.com/palantir/blueprint), which consists of three different scoped packages @palantir but `is_npm_package_name_valid` doesn't allow them. We could replace it by https://github.com/npm/validate-npm-package-name or enhance our existing function.

**Comment by brillout** [comment]
Thanks for opening the issue.
I made [changes](https://github.com/brillout/devarchy/commit/845b17197e4270226ac8c59d3692d21fefdb5a6c#diff-992fca6b680633b003b1069b12ac43e4) and it should work now.

**Comment by troglotit** [comment]
Yeah, it seems to work right now!

**Comment by brillout** [comment]
Upvoted:p:)
